# Generated by Django 2.2.7 on 2019-12-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordlist',
            old_name='word_name',
            new_name='word',
        ),
        migrations.RemoveField(
            model_name='question',
            name='model_answer',
        ),
        migrations.AlterField(
            model_name='song',
            name='song_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='target',
            field=models.IntegerField(),
        ),
    ]
