# Generated by Django 2.2.7 on 2020-01-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191216_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='release_year',
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.CharField(max_length=800),
        ),
    ]
